name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    
    - id: release_version
      run: echo "##[set-output name=versionRelease;]$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      shell: bash

    - run: echo ${{ steps.release_version.outputs.versionRelease }}
      shell: bash

    - run: echo "##[set-output name=payload;]$(curl -H  'Authorization: token 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' https://api.github.com/repos/miask-org/mule-sample-2/releases/tags/1.0.0)"
      shell: bash

    - run: echo $payload

    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
